Modified to accept process.env
NguyenHoanTien/samples pull request #2
Opened 2018-09-26 05:09 UTC by blackheat

2018-09-26 08:18 UTC, tiennguyenhoan requested changes
@blackheat please take a look

2018-09-26 08:18 UTC, NguyenHoanTien commented on javascript/android-web-test.js
const sessionName: process.env.KOBITON_SESSION_NAME || 'Sample session name'

2018-09-26 08:18 UTC, NguyenHoanTien commented on javascript/android-web-test.js
> +  sessionDescription: process.env.KOBITON_SESSION_DESCRIPTION,
same

2018-09-26 08:18 UTC, NguyenHoanTien commented on javascript/android-web-test.js
> +  deviceOrientation:  process.env.KOBITON_SESSION_DEVICE_ORIENTATION,
same

2018-09-26 08:18 UTC, NguyenHoanTien commented on javascript/android-web-test.js
> +  captureScreenshots: process.env.KOBITON_SESSION_CAPTURE_SCREENSHOTS,
same

2018-09-26 08:18 UTC, NguyenHoanTien commented on javascript/android-web-test.js
> +  deviceGroup:        process.env.KOBITON_SESSION_DEVICE_GROUP,
same

2018-09-26 08:18 UTC, NguyenHoanTien commented on javascript/android-web-test.js
> +  browserName:        process.env.KOBITON_SESSION_BROWSER_NAME
same

2018-09-26 08:23 UTC, tiennguyenhoan requested changes

2018-09-26 08:23 UTC, tiennguyenhoan commented on javascript/android-web-test.js
> +  sessionName:        process.env.KOBITON_SESSION_NAME,
const name = process.env.KOBITON_SESSION_NAME  || ''

2018-10-01 07:53 UTC, NguyenHoanTien commented
Your PR sucks !!

2018-10-01 07:53 UTC, closed without merging